language: go
go:
  - 1.8
  - 1.7
  - 1.6

install:
  - go get -u github.com/golang/lint/golint
  - curl https://glide.sh/get | sh
  - glide install

script:
  - make check
  - make build
  - make release
  - make clean
  - make test
  - make test-coverage
