language: go
go:
  - 1.7
  - 1.6

install:
  - go get -u github.com/golang/lint/golint

script:
  - make check
  - make build
  - make release
  - make clean
  - make unit-test
  - make unit-coverage
